DESTDIR=
SUBDIR=/usr/lib/rhythmbox/plugins/icecast/

all:
clean:

install:
	install -d $(DESTDIR)$(SUBDIR)
	install icecast.py $(DESTDIR)$(SUBDIR)
	install icecast.rb-plugin $(DESTDIR)$(SUBDIR)
	install xiph-logo.png $(DESTDIR)$(SUBDIR)
